source 'https://rubygems.org'

gem 'sinatra'
gem 'sequel'
gem 'sqlite3'
gem 'rubyzip'
gem 'rack'
#gem 'yaml'
gem 'json'
gem 'terminal-table'
gem 'uuid'
#
gem 'socket'
gem 'sign_pass', '1.0.0', :path => 'lib/'
#gem 'securerandom'
